### ISSUE TITLE
Unable to download the nightly build / build failed

### ISSUE THREAD

**Issue by julianhemde** [wonderit/indoor-segmentation-android#1]
Hi there,
i am trying to build and run the application on Windows 7 with Android Studio (3.1.4). First of all the link: [https://ci.tensorflow.org/view/Nightly/job/nightly-android/](url) for downloading the nightly build does not work.

Then I tried to use the .so files in libs/armeabi-v7a/ .
I changed in the build.gradle:
`def nativeBuildSystem = 'makefile'`
and:
`demoLibPath = 'E:/tensorflow/indoor-segmentation-android-master/libs/armeabi-v7a/libtensorflow_demo.so'`
`inferenceLibPath = 'E:/tensorflow/indoor-segmentation-android-master/libs/armeabi-v7a/libtensorflow_inference.so'`

But trying to build I get these compiler errors:

org/tensorflow/demo/TensorFlowDeeplabV3PlusDetector.java |  
-- | --
error: cannot find symbol class Graph |  
error: cannot find symbol class Operation |  
error: cannot find symbol class TensorFlowInferenceInterface |  
error: cannot find symbol class TensorFlowInferenceInterface |  
error: cannot find symbol class Operation |  
non-varargs call of varargs method with inexact argument type for last parameter; cast to Object for a varargs call cast to Object[] for a non-varargs call and to suppress this warning |  

I would appreciate every helpful information, since I'm new to TensorFlow and Android Studio.

**Comment by anilsathyan7** [comment]
Try changing package name in manifest to package="org.tensorflow.demo">
Also, I tried adding the following lines at the end of build.gradle and it was built successfully after downloading additional files.

dependencies {
    compile 'org.tensorflow:tensorflow-android:+'
}
But i have a new issue now
It looks like build problem - No Op kernel registered to support Op slice 
The app crashes anyway on mobile !!!

**Comment by julianhemde** [comment]
thanks, worked for me but i have the same issue that the app crashes with following exception in the run window:

> FATAL EXCEPTION: inference
                  Process: org.tensorflow.demo, PID: 12805
                  java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Slice' with these attrs.

**Comment by anilsathyan7** [comment]
It seems the app works fine for  devices with **armeabi-v7**a - 32bit CPU ( ARM Cortex-A5, ARM Cortex-A7, ARM Cortex-A8, ARM Cortex-A9, ARM Cortex-A12, ARM Cortex-A15, ARM Cortex-A17)

But it doesn't work for **arm64-v8a** devices ((Nexus 5x) - 64bit - ARM Cortex-A35, ARM Cortex-A53, ARM Cortex-A57, ARM Cortex-A72, ARM Cortex-A73)
[I used ubuntu 16.04 and the app worked with Moto C Plus with Nougat]

**Comment by wonderit** [comment]
Thanks @anilsathyan7 

I'm trying to build the libtensorflow_inference.so for arm64-v8a, but failing so far...

Here is the link for the solution
[how to register int64 to mobile tensorflow lib](https://github.com/wonderit/indoor-segmentation-android/issues/4#issuecomment-415691986)

**Comment by wonderit** [comment]
I have uploaded the library for arm64-v8a.
